### ISSUE TITLE
Version 2.8.0-RC1 is not available for artifact commons-io:commons-io

### ISSUE THREAD

**Issue by sulakhesagar** [jfrog/documentation#123]
![image](https://github.com/jfrog/documentation/assets/80239543/c026be44-a453-45c4-8e86-4b89901c9552)
Could you please help us to resolve below error:
When executing FrogBot on Auto Scanning PR and Push For Fix in Azure Pipeline, the following error occurs:

[ERROR] Failed to execute goal org.codehaus.mojo:versions-maven-plugin:2.16.2:use-dep-version (default-cli) on project XXX: Version 2.8.0-RC1 is not available for artifact commons-io:commons-io
Below are the versions we are using to
Artifactory 7.77.11
Xray 3.91.3

**Comment by eyalbe4** [comment]
@sulakhesagar,
Will you be able to close this issue, and reopen it under github.com/jfrog/frogbot, so that relevant team sees this communication?

**Comment by sulakhesagar** [comment]
https://github.com/jfrog/frogbot/issues/695

**Comment by sulakhesagar** [comment]
https://github.com/jfrog/frogbot/issues/695
