### ISSUE TITLE
Typos on JFrog CLI authentication page

### ISSUE THREAD

**Issue by rpjday** [jfrog/documentation#154]
From authentication.md:

"JFrog CLI automatically refreshed the token ..." refreshes?

"or work[s] with JFrog Distribution."

"or use the --`client-cert-path` and`--client-cert-ket-path` command"

- first double dashes should be *inside* backquotes
- "ket" -> "key"

**Comment by eyalbe4** [comment]
Thanks for reporting this issue!
I'm closing this issue, since very soon the option for openning issues in this repository will be cancelled.
We'd welcome pull requests with documentation corrections and improvements to this repository.
