### ISSUE TITLE
Git provider icons do not show up properly on the new docs site

### ISSUE THREAD

**Issue by leapfrogger** [jfrog/documentation#60]
Hi,

Looking at the following - 

https://github.com/jfrog/documentation/blob/ab691d15850bce4c6deebfae6347cebe4cad9c2c/jfrog-applications/frogbot/README.md?plain=1#L14

These logos are of low size and thus show up pixelated when viewed on the new docs site [here](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot). The same is true for the package manager logos.

Please either find higher size images or use SVG images which autoscale.

Thanks,
Nitin Khanna

**Comment by eyalbe4** [comment]
Thanks for reporting this @leapfrogger. 
I believe this issue has been fixed. 
Please feel free to reopen this issue if you see otherwise.
