### ISSUE TITLE
In correct link tagged for "on-demand binary scanning" text in Scan your Binaries wiki

### ISSUE THREAD

**Issue by Sankardunga** [jfrog/documentation#82]
**Issue Description:**

Referring to the hyper link tagged for "on-demand binary scanning" text in below article, which is navigating to a page which needs to authentication
   https://docs.jfrog-applications.jfrog.io/jfrog-applications/jfrog-cli/cli-for-jfrog-security/scan-your-binaries

Please tag correct link here, I believe this should navigate to https://jfrog.com/help/r/jfrog-security-documentation/xray-on-demand-binary-scan.

**Comment by eyalbe4** [comment]
Thanks for reporting this @Sankardunga, we would however prefer pull requests to this repository rather than issues.

**Comment by Sankardunga** [comment]
Thanks @eyalbe4. Created a pull request https://github.com/jfrog/documentation/pull/83
